import os
import streamlit as st
import numpy as np
import cv2
from PIL import Image
from fpdf import FPDF
from datetime import datetime

# --- KONFIGURASI HALAMAN ---
st.set_page_config(
    page_title="NeuroScan AI | Diagnostic",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- FUNGSI GENERATE PDF ---
def create_pdf(label, confidence, probabilities):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(26, 115, 232)
    pdf.cell(0, 15, "NEUROSCAN AI - DIAGNOSTIC REPORT", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. FINAL DIAGNOSIS", ln=True)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, f"Classification Result: {label.upper()}", ln=True)
    pdf.cell(0, 10, f"Confidence Level: {confidence:.2f}%", ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "2. PROBABILITY DISTRIBUTION", ln=True)
    pdf.set_font("Arial", '', 12)
    for name, prob in probabilities.items():
        pdf.cell(0, 10, f"- {name}: {prob:.2f}%", ln=True)
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI system (ResNet50) for research purposes. All results must be verified by a certified medical professional.")
    return pdf.output(dest='S').encode('latin-1')

# --- INJEKSI CSS DARK MODE & POPPINS ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap');

    /* Kunci Tema Dark Mode Secara Global */
    html, body, [class*="css"], .stApp {
        font-family: 'Poppins', sans-serif;
        background-color: #0E1117 !important;
        color: #FFFFFF !important;
    }

    /* Memaksa semua teks markdown jadi putih */
    .stMarkdown, p, span, label, h1, h2, h3, h4, h5, h6 {
        color: #FFFFFF !important;
    }

    /* Card Hasil - Abu-abu Gelap agar kontras */
    .metric-card {
        background-color: #161B22 !important;
        padding: 30px;
        border-radius: 16px;
        border: 1px solid #30363D;
        box-shadow: 0 4px 20px rgba(0,0,0,0.4);
        margin-bottom: 25px;
        text-align: center;
    }

    .result-value {
        font-size: 42px;
        font-weight: 800;
        color: #58A6FF !important; /* Biru Neon untuk Dark Mode */
        margin: 15px 0;
        letter-spacing: 1px;
    }

    /* Sidebar Styling */
    [data-testid="stSidebar"] {
        background-color: #0D1117 !important;
        border-right: 1px solid #30363D;
    }

    /* Button Styling */
    .stButton>button {
        width: 100%;
        border-radius: 12px;
        padding: 12px;
        background-color: #238636 !important; /* Hijau GitHub Style */
        color: white !important;
        border: none;
        font-weight: 700;
        font-family: 'Poppins', sans-serif;
        transition: 0.3s;
    }
    .stButton>button:hover {
        background-color: #2EA043 !important;
        box-shadow: 0 0 15px rgba(35, 134, 54, 0.4);
    }

    /* Progress Bar */
    .stProgress > div > div > div > div {
        background-color: #58A6FF !important;
    }

    /* Fix File Uploader Text */
    [data-testid="stFileUploadDropzone"] p {
        color: #8B949E !important;
    }
    </style>
    """, unsafe_allow_html=True)

# --- LOAD MODEL ---
@st.cache_resource
def load_onnx_model():
    try:
        import onnxruntime as ort
        model_path = 'resnet_model.onnx'
        if not os.path.exists(model_path): return None
        return ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
    except:
        return None

# --- SIDEBAR ---
with st.sidebar:
    st.markdown("<h1 style='font-size:26px; font-weight:800; color:#58A6FF; margin-bottom:0;'>NEUROSCAN</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#8B949E; font-size:12px;'>Precision MRI Analysis v1.0</p>", unsafe_allow_html=True)
    st.markdown("---")
    st.markdown("<h4 style='font-size:16px;'>System Diagnostic</h4>", unsafe_allow_html=True)
    st.success("● Engine: ResNet50 Active")
    st.info("● Mode: ONNX Optimized")
    
    if st.button("System Reboot"):
        st.cache_resource.clear()
        st.rerun()

# --- MAIN CONTENT ---
st.markdown("<h1 style='font-weight:800; letter-spacing:-1px;'>Diagnostic Dashboard</h1>", unsafe_allow_html=True)
st.markdown("<p style='color:#8B949E; font-size:16px;'>Layanan klasifikasi tumor otak berbasis Deep Learning (ResNet50).</p>", unsafe_allow_html=True)

session = load_onnx_model()

if session is None:
    st.error("FATAL ERROR: 'resnet_model.onnx' not found in directory.")
else:
    col_l, col_r = st.columns([1, 1], gap="large")

    with col_l:
        st.markdown("<h4 style='font-weight:600; margin-bottom:15px;'>Patient Scan Data</h4>", unsafe_allow_html=True)
        uploaded_file = st.file_uploader("", type=["jpg", "png", "jpeg"])
        
        if uploaded_file:
            image = Image.open(uploaded_file).convert('RGB')
            st.image(image, use_container_width=True)
            analyze_btn = st.button('RUN NEURAL INFERENCE')

    with col_r:
        st.markdown("<h4 style='font-weight:600; margin-bottom:15px;'>Analytical Result</h4>", unsafe_allow_html=True)
        
        if uploaded_file and analyze_btn:
            with st.spinner('AI is computing...'):
                try:
                    # Preprocessing
                    img_224 = image.resize((224, 224))
                    img_array = np.array(img_224).astype('float32')
                    img_array = img_array[:, :, ::-1] # BGR conversion
                    img_array[:, :, 0] -= 103.939
                    img_array[:, :, 1] -= 116.779
                    img_array[:, :, 2] -= 123.68
                    img_batch = np.expand_dims(img_array, axis=0)

                    # Prediction
                    input_name = session.get_inputs()[0].name
                    output = session.run(None, {input_name: img_batch})[0]
                    
                    CLASS_NAMES = {0: "Glioma", 1: "Meningioma", 2: "No Tumor", 3: "Pituitary"}
                    pred_idx = int(np.argmax(output[0]))
                    confidence = float(np.max(output[0])) * 100
                    label = CLASS_NAMES.get(pred_idx, "Unknown")
                    
                    probs_dict = {CLASS_NAMES[i]: float(output[0][i])*100 for i in range(4)}

                    # Result Card
                    st.markdown(f"""
                        <div class="metric-card">
                            <p style="font-size:12px; font-weight:600; color:#8B949E; text-transform:uppercase;">Predicted Pathology</p>
                            <div class="result-value">{label.upper()}</div>
                            <p style="font-size:16px; color:#C9D1D9;">Confidence: <b>{confidence:.2f}%</b></p>
                        </div>
                    """, unsafe_allow_html=True)

                    # PDF Button
                    pdf_data = create_pdf(label, confidence, probs_dict)
                    st.download_button(
                        label="📄 Download Medical Report (PDF)",
                        data=pdf_data,
                        file_name=f"Report_{label}_{datetime.now().strftime('%Y%m%d')}.pdf",
                        mime="application/pdf"
                    )

                    st.markdown("<br><p style='font-weight:600; font-size:13px; color:#8B949E;'>PROBABILITY MAPPING</p>", unsafe_allow_html=True)
                    for name, prob_val in probs_dict.items():
                        st.markdown(f"<span style='font-size:13px;'>{name} ({prob_val:.1f}%)</span>", unsafe_allow_html=True)
                        st.progress(prob_val / 100)

                except Exception as e:
                    st.error(f"Error during analysis: {e}")
        else:
            st.markdown("""
                <div style='text-align:center; padding: 100px 20px; border: 2px dashed #30363D; border-radius:16px; background-color: #161B22;'>
                    <p style='color:#8B949E; font-size:14px;'>Silakan unggah citra untuk memulai diagnosis otomatis.</p>
                </div>
            """, unsafe_allow_html=True)

# --- FOOTER ---
st.markdown("<br><br><div style='text-align:center; color:#484F58; font-size:11px; border-top: 1px solid #30363D; padding-top:20px;'>NeuroScan AI | Deep Learning Framework | IEEE Journal Documentation</div>", unsafe_allow_html=True)
