import os
import streamlit as st
import numpy as np
import cv2
import time
from PIL import Image
from fpdf import FPDF
from datetime import datetime

# --- KONFIGURASI HALAMAN ---
st.set_page_config(
    page_title="NeuroScan AI | Precision Diagnostic",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- FUNGSI GENERATE PDF ---
def create_pdf(label, confidence, probabilities):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(26, 115, 232)
    pdf.cell(0, 15, "NEUROSCAN AI - DIAGNOSTIC REPORT", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. FINAL DIAGNOSIS", ln=True)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, f"Classification Result: {label.upper()}", ln=True)
    pdf.cell(0, 10, f"Confidence Level: {confidence:.2f}%", ln=True)
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "2. PROBABILITY DISTRIBUTION", ln=True)
    pdf.set_font("Arial", '', 12)
    for name, prob in probabilities.items():
        pdf.cell(0, 10, f"- {name}: {prob:.2f}%", ln=True)
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by a Deep Learning system (ResNet50) for research purposes. All results must be verified by a certified medical professional.")
    return pdf.output(dest='S').encode('latin-1')

# --- INJEKSI CSS DARK MODE + POPPINS + GLOW EFFECT ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap');

    html, body, [class*="css"], .stApp {
        font-family: 'Poppins', sans-serif;
        background-color: #0B0E14 !important;
        color: #FFFFFF !important;
    }

    .stMarkdown, p, span, label, h1, h2, h3, h4, h5, h6 {
        color: #FFFFFF !important;
    }

    /* Metric Card Modern */
    .metric-card {
        background-color: #161B22 !important;
        padding: 25px;
        border-radius: 20px;
        border: 1px solid #30363D;
        box-shadow: 0 10px 30px rgba(0,0,0,0.5);
        margin-bottom: 20px;
        transition: transform 0.3s ease;
    }
    .metric-card:hover {
        transform: translateY(-5px);
        border-color: #58A6FF;
    }

    .result-value {
        font-size: 48px;
        font-weight: 800;
        color: #58A6FF !important;
        margin: 10px 0;
        text-shadow: 0 0 15px rgba(88, 166, 255, 0.3);
    }

    /* Sidebar Styling */
    [data-testid="stSidebar"] {
        background-color: #0D1117 !important;
        border-right: 1px solid #30363D;
    }

    /* Button Styling Neon */
    .stButton>button {
        width: 100%;
        border-radius: 12px;
        padding: 15px;
        background: linear-gradient(135deg, #238636 0%, #2EA043 100%) !important;
        color: white !important;
        border: none;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 1px;
        transition: 0.4s;
    }
    .stButton>button:hover {
        box-shadow: 0 0 20px rgba(46, 160, 67, 0.6);
        transform: scale(1.02);
    }

    /* Info Pills */
    .info-pill {
        background-color: #1F2937;
        padding: 5px 15px;
        border-radius: 50px;
        font-size: 12px;
        border: 1px solid #374151;
        display: inline-block;
        margin-right: 10px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- LOAD MODEL ---
@st.cache_resource
def load_onnx_model():
    try:
        import onnxruntime as ort
        model_path = 'resnet_model.onnx'
        if not os.path.exists(model_path): return None
        return ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
    except:
        return None

# --- SIDEBAR ---
with st.sidebar:
    st.markdown("<h1 style='font-size:28px; font-weight:800; color:#58A6FF;'>NEUROSCAN AI</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#8B949E; font-size:12px; margin-bottom:20px;'>Precision Neurology Inference</p>", unsafe_allow_html=True)
    
    with st.expander("🩺 Clinical Background", expanded=False):
        st.caption("Model ini dilatih menggunakan dataset gabungan Figshare, SARTAJ, dan Br35H (7.200 citra MRI) untuk mendeteksi 4 kategori tumor otak.")

    st.markdown("---")
    st.markdown("<h4 style='font-size:14px; color:#8B949E;'>SYSTEM MONITOR</h4>", unsafe_allow_html=True)
    st.success("● Engine ResNet50: Ready")
    st.info("● Optimization: ONNX")
    
    if st.button("REBOOT SYSTEM"):
        st.cache_resource.clear()
        st.rerun()

# --- MAIN CONTENT ---
st.markdown("<h1 style='font-weight:800; font-size:42px; letter-spacing:-1.5px;'>Neuro-Inference Dashboard</h1>", unsafe_allow_html=True)
st.markdown("""
    <div style='margin-bottom: 25px;'>
        <span class='info-pill'>v1.2 Stable</span>
        <span class='info-pill'>ResNet-50 Backend</span>
        <span class='info-pill'>IEEE Journal Standard</span>
    </div>
""", unsafe_allow_html=True)

session = load_onnx_model()

if session is None:
    st.error("FATAL ERROR: 'resnet_model.onnx' not found.")
else:
    col_l, col_r = st.columns([1, 1], gap="large")

    with col_l:
        st.markdown("<h4 style='font-weight:600; color:#8B949E;'>PATIENT SCAN INPUT</h4>", unsafe_allow_html=True)
        uploaded_file = st.file_uploader("", type=["jpg", "png", "jpeg"])
        
        if uploaded_file:
            image = Image.open(uploaded_file).convert('RGB')
            st.image(image, use_container_width=True)
            analyze_btn = st.button('GENERATE DIAGNOSTIC ANALYSIS')

    with col_r:
        st.markdown("<h4 style='font-weight:600; color:#8B949E;'>DIAGNOSTIC FINDINGS</h4>", unsafe_allow_html=True)
        
        if uploaded_file and analyze_btn:
            start_time = time.time()
            with st.spinner('Neural Network is processing MRI slices...'):
                try:
                    # Preprocessing
                    img_224 = image.resize((224, 224))
                    img_array = np.array(img_224).astype('float32')
                    img_array = img_array[:, :, ::-1] # BGR
                    img_array[:, :, 0] -= 103.939
                    img_array[:, :, 1] -= 116.779
                    img_array[:, :, 2] -= 123.68
                    img_batch = np.expand_dims(img_array, axis=0)

                    # Prediction
                    input_name = session.get_inputs()[0].name
                    output = session.run(None, {input_name: img_batch})[0]
                    
                    end_time = time.time()
                    inference_speed = (end_time - start_time) * 1000

                    CLASS_NAMES = {0: "Glioma", 1: "Meningioma", 2: "No Tumor", 3: "Pituitary"}
                    pred_idx = int(np.argmax(output[0]))
                    confidence = float(np.max(output[0])) * 100
                    label = CLASS_NAMES.get(pred_idx, "Unknown")
                    
                    probs_dict = {CLASS_NAMES[i]: float(output[0][i])*100 for i in range(4)}

                    # Result Card
                    st.markdown(f"""
                        <div class="metric-card">
                            <p style="font-size:12px; font-weight:700; color:#8B949E; text-transform:uppercase; letter-spacing:1px;">Primary Classification</p>
                            <div class="result-value">{label.upper()}</div>
                            <p style="font-size:16px; color:#C9D1D9;">Probability Score: <b style="color:#58A6FF;">{confidence:.2f}%</b></p>
                            <p style="font-size:11px; color:#8B949E;">Inference Speed: {inference_speed:.2f}ms</p>
                        </div>
                    """, unsafe_allow_html=True)

                    # Action Buttons
                    pdf_data = create_pdf(label, confidence, probs_dict)
                    st.download_button(
                        label="📄 DOWNLOAD CLINICAL REPORT (PDF)",
                        data=pdf_data,
                        file_name=f"NeuroScan_{label}_{datetime.now().strftime('%H%M')}.pdf",
                        mime="application/pdf"
                    )

                    st.markdown("<br><p style='font-weight:700; font-size:12px; color:#8B949E; text-transform:uppercase;'>Neural Probability Mapping</p>", unsafe_allow_html=True)
                    for name, prob_val in probs_dict.items():
                        st.markdown(f"<span style='font-size:13px;'>{name}</span> <span style='float:right; font-size:13px; color:#58A6FF;'>{prob_val:.1f}%</span>", unsafe_allow_html=True)
                        st.progress(prob_val / 100)

                except Exception as e:
                    st.error(f"Computation Error: {e}")
        else:
            st.markdown("""
                <div style='text-align:center; padding: 100px 20px; border: 2px dashed #30363D; border-radius:24px; background-color: #161B22;'>
                    <p style='color:#8B949E; font-size:16px; font-weight:300;'>Awaiting Image Data Sequence...</p>
                    <p style='color:#484F58; font-size:12px;'>Upload MRI scan to activate Neural Inference Engine</p>
                </div>
            """, unsafe_allow_html=True)

# --- FOOTER ---
st.markdown("<br><br><br>", unsafe_allow_html=True)
st.markdown("""
    <div style='border-top: 1px solid #30363D; padding-top:25px; text-align: center;'>
        <p style='color: #484F58; font-size: 11px; letter-spacing: 1px;'>
            NEUROSCAN AI v1.2 | IEEE DOCUMENTATION COMPLIANT | © 2026 RESEARCH LAB
        </p>
    </div>
""", unsafe_allow_html=True)
