import os
import streamlit as st
import numpy as np
import cv2
from PIL import Image
from fpdf import FPDF
import base64
from datetime import datetime

# --- KONFIGURASI HALAMAN ---
st.set_page_config(
    page_title="NeuroScan AI | Diagnostic",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- FUNGSI GENERATE PDF ---
def create_pdf(label, confidence, probabilities):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(26, 115, 232) # Biru
    pdf.cell(0, 15, "NEUROSCAN AI - DIAGNOSTIC REPORT", ln=True, align='C')
    
    pdf.set_font("Arial", size=10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
    pdf.ln(10)
    
    # Diagnosis Result
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0) # Hitam
    pdf.cell(0, 10, "1. FINAL DIAGNOSIS", ln=True)
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, f"Classification Result: {label.upper()}", ln=True)
    pdf.cell(0, 10, f"Confidence Level: {confidence:.2f}%", ln=True)
    pdf.ln(5)
    
    # Probabilities
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "2. PROBABILITY DISTRIBUTION", ln=True)
    pdf.set_font("Arial", '', 12)
    for name, prob in probabilities.items():
        pdf.cell(0, 10, f"- {name}: {prob:.2f}%", ln=True)
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI system (ResNet50) for research purposes. All results must be verified by a certified medical professional.")
    
    return pdf.output(dest='S').encode('latin-1')

# --- INJEKSI CSS KONSISTEN (BIRU & HITAM) ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');

    /* Kunci Warna Background & Font */
    html, body, [class*="css"], .stApp {
        font-family: 'Inter', sans-serif;
        background-color: #F0F2F6 !important;
        color: #1A1A1A !important;
    }

    /* Sidebar - Biru Gelap ke Hitam */
    [data-testid="stSidebar"] {
        background-color: #0F172A !important;
        color: #FFFFFF !important;
    }
    [data-testid="stSidebar"] * {
        color: #FFFFFF !important;
    }

    /* Metric Card - Putih Kontras Tinggi */
    .metric-card {
        background-color: #FFFFFF !important;
        padding: 30px;
        border-radius: 12px;
        border: 2px solid #E2E8F0;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        margin-bottom: 20px;
        color: #000000 !important;
    }

    .result-value {
        font-size: 40px;
        font-weight: 800;
        color: #1E40AF !important; /* Biru Tua */
        margin: 10px 0;
    }

    /* Tombol Utama */
    .stButton>button {
        background-color: #2563EB !important;
        color: white !important;
        border-radius: 8px;
        font-weight: 700;
        padding: 12px;
        border: none;
        transition: 0.3s;
    }
    .stButton>button:hover {
        background-color: #1E40AF !important;
        box-shadow: 0 4px 15px rgba(37, 99, 235, 0.4);
    }

    /* Progress Bar Color */
    .stProgress > div > div > div > div {
        background-color: #2563EB !important;
    }
    </style>
    """, unsafe_allow_html=True)

# --- LOAD MODEL ---
@st.cache_resource
def load_onnx_model():
    try:
        import onnxruntime as ort
        model_path = 'resnet_model.onnx'
        if not os.path.exists(model_path): return None
        return ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
    except:
        return None

# --- SIDEBAR ---
with st.sidebar:
    st.markdown("<h1 style='font-size:24px; font-weight:800; color:#38BDF8;'>NEUROSCAN AI</h1>", unsafe_allow_html=True)
    st.markdown("<p style='opacity:0.7;'>Precision MRI Diagnostics</p>", unsafe_allow_html=True)
    st.markdown("---")
    st.write("**System Status:**")
    st.success("🟢 Connected to ResNet50")
    st.caption("Mode: Industrial Inference")
    st.caption("Architecture: ONNX Optimized")

# --- MAIN DASHBOARD ---
st.markdown("<h1 style='color:#0F172A; font-weight:800;'>Automated MRI Analysis</h1>", unsafe_allow_html=True)
st.markdown("<p style='color:#475569; font-size:18px;'>Analisis Citra Otak Menggunakan Jaringan Saraf Konvolusional (CNN).</p>", unsafe_allow_html=True)

session = load_onnx_model()

if session is None:
    st.error("FATAL ERROR: 'resnet_model.onnx' tidak ditemukan.")
else:
    col_left, col_right = st.columns([1, 1], gap="large")

    with col_left:
        st.markdown("<h4 style='font-weight:700;'>1. Data Acquisition</h4>", unsafe_allow_html=True)
        uploaded_file = st.file_uploader("Upload citra MRI pasien (Format: JPG, PNG)", type=["jpg", "png", "jpeg"])
        
        if uploaded_file:
            image = Image.open(uploaded_file).convert('RGB')
            st.image(image, use_container_width=True)
            analyze_btn = st.button('GENERATE DIAGNOSTIC REPORT')

    with col_right:
        st.markdown("<h4 style='font-weight:700;'>2. Neural Analysis</h4>", unsafe_allow_html=True)
        
        if uploaded_file and analyze_btn:
            with st.spinner('AI sedang memproses citra...'):
                try:
                    # Preprocessing
                    img_224 = image.resize((224, 224))
                    img_array = np.array(img_224).astype('float32')
                    img_array = img_array[:, :, ::-1] # BGR
                    img_array[:, :, 0] -= 103.939
                    img_array[:, :, 1] -= 116.779
                    img_array[:, :, 2] -= 123.68
                    img_batch = np.expand_dims(img_array, axis=0)

                    # Prediction
                    input_name = session.get_inputs()[0].name
                    output = session.run(None, {input_name: img_batch})[0]
                    
                    CLASS_NAMES = {0: "Glioma", 1: "Meningioma", 2: "No Tumor", 3: "Pituitary"}
                    pred_idx = int(np.argmax(output[0]))
                    confidence = float(np.max(output[0])) * 100
                    label = CLASS_NAMES.get(pred_idx, "Unknown")
                    
                    # Simpan probabilitas untuk PDF
                    probs_dict = {CLASS_NAMES[i]: float(output[0][i])*100 for i in range(4)}

                    # Card Hasil
                    st.markdown(f"""
                        <div class="metric-card">
                            <div style="font-size:14px; font-weight:700; color:#64748B;">FINAL DIAGNOSIS</div>
                            <div class="result-value">{label.upper()}</div>
                            <div style="font-size:16px; color:#1E293B;">Confidence Score: <b>{confidence:.2f}%</b></div>
                        </div>
                    """, unsafe_allow_html=True)

                    # Download PDF Button
                    pdf_data = create_pdf(label, confidence, probs_dict)
                    st.download_button(
                        label="📄 Download Diagnostic Report (PDF)",
                        data=pdf_data,
                        file_name=f"NeuroScan_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                        mime="application/pdf"
                    )

                    st.markdown("<br><p style='font-weight:700; font-size:14px;'>PROBABILITY BREAKDOWN</p>", unsafe_allow_html=True)
                    for name, prob_val in probs_dict.items():
                        st.write(f"{name} ({prob_val:.1f}%)")
                        st.progress(prob_val / 100)

                except Exception as e:
                    st.error(f"Error: {e}")
        else:
            st.markdown("""
                <div style='text-align:center; padding: 100px 20px; border: 2px dashed #CBD5E1; border-radius:12px; background-color: #FFFFFF;'>
                    <p style='color:#94A3B8;'>Sistem siap. Silakan unggah citra MRI.</p>
                </div>
            """, unsafe_allow_html=True)

# --- FOOTER ---
st.markdown("<br><br><div style='text-align:center; color:#64748B; font-size:12px; border-top: 1px solid #E2E8F0; padding-top:20px;'>NeuroScan AI v1.0 | Clinical Research Application | © 2026</div>", unsafe_allow_html=True)
